Visual
imirrori/LevelUpGame2023 pull request #3
Opened 2023-03-22 16:15 UTC by Lervaler

PR на мердж в dev (пробный)

2023-03-22 17:09 UTC, DmitrTRC requested changes

2023-03-22 17:09 UTC, DmitrTRC commented on Game/main.cpp
> +    glutInit(&argc, argv);  //возможно внести в часть класса?
All game initializers should be moved to class Game

2023-03-22 17:11 UTC, DmitrTRC commented
@Lervaler  
Move the Initializer procedures to Game class

2023-03-24 09:35 UTC, DmitrTRC commented
Валерия
1) Не очень хорошо наследование класса Game - он предполагался  как верхнеуровневый. Используй агрегацию
2) Своевременно подтягивай себе dev - для учета изменений и разрешения конфликтов. Иначе мы будем тянуть в разные стороны. Я придерживаюсь концепции которую МЫ вроде как между собой согласовали!

2023-03-24 09:37 UTC, DmitrTRC requested changes

2023-03-24 09:37 UTC, DmitrTRC commented on Game/Game.h
> +    : public Visual::Visualizer
Aggregation instead of Inheritance

2023-03-25 10:47 UTC, Lervaler commented on Game/main.cpp
> +    glutInit(&argc, argv);  //возможно внести в часть класса?
исправлено

2023-03-25 10:48 UTC, Lervaler commented on Game/Visualizer.cpp
> +    glutInitWindowSize(640,480);
не исправлено, ждем Владимира

2023-03-25 10:48 UTC, Lervaler commented on Game/Game.h
> +    : public Visual::Visualizer
агрегация выполнена, нужна проверка)) правильно ли?

2023-03-25 11:06 UTC, merged